runtime: php55
api_version: 1

handlers:
# Serve images as static resources.
- url: /images
  static_dir: images

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /font
  static_dir: font
  
- url: /ISAF
  static_dir: ISAF

- url: /dev
  static_dir: dev
  
- url: /guide
  static_dir: guide
  
- url: /member
  static_dir: member
  
- url: /online
  static_dir: online
  
- url: /main
  static_dir: main

- url: /main/.*
  script: /main/main.php

- url: /.*
  script: /main/main.php
